config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'
  get '/blog', to: 'static_pages#blog'
  get '/service', to: 'static_pages#service'
  get '/new', to: 'products#new'
  get '/show', to: 'products#show'
  post '/filter_price', to: 'static_pages#filter_price', :format => false
  get 'filter_price', to: 'static_pages#filter_price'
  resources :products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :avatar

    scope :filtered, ->(filter_param) {where(:description => filter_param)}
    scope :vegetarian, ->() {where(:vegetarian => "true")}
    scope :filter_price, ->(slide1,slide2) {where("price>? AND price<?",slide1,slide2)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
        
  def home
    
  end

  def contact
  end
  
  def about
  end

  def help
  end

 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController 
    def index
    
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            @product.avatar.attach(params[:product][:avatar])
            redirect_to root_path
        else
            redirect_to new_product_path
        end

    end

    def show

    end

    private 
        def product_params
            params.require(:product).permit(:title, :description, :price, :vegetarian)
        end
    # def update
    #     @user = User.find(params[:id])
    #     avatar = params[:user][:avatar]
    #     if @user.update(user_params)
    #         if avatar
    #         @user.avatar.attach(avatar)
    #         end
    #         redirect_to @user, notice: "Your profile has been updated"
    #     else
    #         render 'edit'
    #     end
    #     end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
     
  def home
    @products = Product.all
    if !params[:type].nil?
      @products = Product.filtered(params[:type])
    elsif params[:sort_type] == "Ascending"
      @products = @products.order(price: :asc )
    elsif params[:sort_type] == "Descending"
      @products = @products.order(price: :desc )
    elsif !params[:veg_type].nil?
      @products = Product.vegetarian
    else
      @products = Product.all
    end  
  end

  def contacts
  end
  
  def about
  end

  def filter_price
    if !params.nil?
      @products = Product.filter_price(params[:slide1].to_i,params[:slide2].to_i)
      respond_to do |format|
        format.js
      end
    end
  end

  def help
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %hr
    %h3.text-center
      Amarok Team
      %p
        %small
          Made by 
          %strong  
            Popa Florian

app/views/layouts/_header.html.haml
%nav.nav.navbar.navbar-expand-sm.justify-content-end.navtop.top
  %a#nav-img.nav-item
    %img{:height => "60", :src => "assets/coffe.png", :width => "60"}
    %strong Eureka Caffe
  %ul.navbar-nav{:style => "float:right"}
    %li.nav-item
      %a.nav-link
        =link_to"Home" , root_path
        %span{:style => "color:orangered"}
          &middot 
    %li.nav-item
      %a.nav-link
        =link_to"About", about_path
        %span{:style => "color:orangered"} 
          &middot
    %li.nav-item
      %a.nav-link
        =link_to"Service", service_path
        %span{:style => "color:orangered"}
          &middot 
    %li.nav-item
      %a.nav-link
        =link_to"Blog", blog_path
        %span{:style => "color:orangered"} 
          &middot
    %li.nav-item
      %a.nav-link
        =link_to"Contacts", contacts_path

app/views/layouts/_midnav.html.haml
%div.midnav
  %nav.nav.navbar.navbar-expand-sm.bg-light.navbar-light
    %ul.navbar-nav
      %li.nav-item
        .dropdown
          %a#navbardrop.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %strong 
              Category
              %span.caret
          %ul.dropdown-menu
            %li
              %a.dropdown-item
                = link_to "Entrees", {:controller => "static_pages", :action => "home", :type => 'Entrees' }
            %li
              %a.dropdown-item
                = link_to "Salads", {:controller => "static_pages", :action => "home", :type => 'Salads' }
            %li
              %a.dropdown-item
                = link_to "Second Courses", {:controller => "static_pages", :action => "home", :type => 'Second Courses' }
            %li
              %a.dropdown-item
                = link_to "Show Menu", root_path
      %li.nav-item
        .dropdown
          %a#navbardrop.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %strong 
              Sorting
              %span.caret
          %ul.dropdown-menu
            %li
              %a.dropdown-item
              = link_to "Ascending", {:controller => "static_pages", :action => "home", :sort_type => 'Ascending' }
            %li
              %a.dropdown-item
              = link_to "Descending", {:controller => "static_pages", :action => "home", :sort_type => 'Descending' }
      %li.nav-item
        .dropdown
          %a#navbardrop.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %strong 
              Vegetarian
              %span.caret
          %ul.dropdown-menu
            %li
              %a.dropdown-item
                =link_to "Vegetarian Food", {:controller => "static_pages", :action => "home" , :veg_type =>true  }
            %li
              %a.dropdown-item                
                = link_to "Show Menu", root_path

    %ul
      %span#slider-price
        %p
          Price
          %span.rangeValues
        %section.range-slider
          %span.rangeValues
          %input.button-slider-1{:max => "150", :min => "0", :type => "range", :value => "50"}
          %input.button-slider-2{:max => "150", :min => "0", :type => "range", :value => "10"}

app/views/layouts/_products.html.haml
.container.pt-5
    .row
        - @products.each do |p|
            .col-md-3
                %p.menu-image-wrapper
                    -if p.avatar.attached?
                        =image_tag(p.avatar)
                .item-details.text-center
                    %h4
                        %strong
                            =p.title
                    %h6.type        
                        =p.description
                    %h6.price
                        $
                        =p.price   
                

app/views/layouts/_texttop.html.haml
.jumbotron{:style => "background-color: transparent"}
  %h1{:align => "center"} Ordering Food
  %p{:align => "center"} 
    Maecenas vel tellus at magna sagittis venenatis.Integer pretium auctor 
  %p{:align => "center"}
    magna, egestas justo gravida vitae.In lacinia auctor auctor
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %title EurekaCaffe
    %link{:href => "assets/images.png", :rel => "shortcut icon"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    =render 'layouts/footer'

    
    
     

      

app/views/products/new.html.haml
= form_for @product do |f|
    Product name: 
    %br
    = f.text_area :title
    %br
    Category:
    %br
    = f.text_area :description
    %br
    Price: 
    %br
    = f.text_area :price
    %br
    = f.file_field :avatar
    %br 
    Vegetarian:
    %br
    = f.check_box :vegetarian , {}, true, false
    %br
    = f.submit "Create"

app/views/static_pages/about.html.haml
%a.previous
    =link_to "Home" , root_path
%h1.text-center
    %strong
        About page

app/views/static_pages/blog.html.haml
%a.previous
    =link_to "Home" , root_path
%h1.text-center
    %strong
        Blog page

app/views/static_pages/contacts.html.haml
%a.previous
    =link_to "Home" , root_path   
%h1.text-center
    %strong.text-center
        Contacts page                               |

app/views/static_pages/filter_price.js.erb
$('.products').html("<%= escape_javascript(render(:partial => 'layouts/products', locals: { products: @products })) %>");

app/views/static_pages/home.html.haml
.jumbotron.jumbotron-home
    %div.jumbotron-top.responsive
        = render 'layouts/header'
        = render 'layouts/texttop'
= render 'layouts/midnav'
.products
    = render 'layouts/products'

app/views/static_pages/service.html.haml
%a.previous
    =link_to "Home" , root_path
%h1.text-center
    %strong
        Service page